name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.5]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, fileinfo, filter, gd, iconv, json, libxml, openssl, pcre, phar, simplexml, tokenizer, xml, xmlwriter, xdebug
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run linting
        run: composer lint

      - name: Run static analysis
        run: composer stan

      - name: Run test suite
        run: composer test
